default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  host: 127.0.0.1
  socket: /Applications/MAMP/tmp/mysql/mysql.sock

development:
  <<: *default
  database: ZenHackImage_development

test:
  <<: *default
  database: ZenHackImage_test

production:
  <<: *default
  database: ZenHackImage_production
